# Generated by Django 4.1.7 on 2023-04-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_article_read_state_article_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
